# You should not need to modify this file. Please modify the variables in your .env file instead. The env-template.txt
# file contains an example .env file with default values pre-populated.
version: "2.4"

services:

  pingdatagovernance:
    image: ${PDG_SIDEBAND_DEVOPS_REGISTRY}/pingdatagovernance:${PDG_SIDEBAND_DEVOPS_TAG}
    container_name: pingdatagovernance
    environment:
      - SERVER_PROFILE_URL=${PDG_SIDEBAND_PROFILE_URL:-https://github.com/pingidentity/pdg-sideband-test-environment.git}
      - SERVER_PROFILE_PATH=server-profiles/pingdatagovernance
      - SERVER_PROFILE_BRANCH=${PDG_SIDEBAND_PROFILE_BRANCH:-main}
      - PDG_SIDEBAND_REQUEST_CONTEXT_METHOD=${PDG_SIDEBAND_REQUEST_CONTEXT_METHOD:-state}
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "${PDG_SIDEBAND_DG_PORT:-7443}:443"
